[[main]]
  name = "Home"
  url = ""
  weight = -110

# [[main]]
#   name = "Archives"
#   url = ""
#   weight = -109
[[main]]
  name = "About"
  url = "about/"
  weight = -108

[[main]]
  name = "VMware"
  url = "/categories/vmware/"
  weight = -107


[[main]]
  name = "VMware"
  url = "categories/vmware/"
  weight = -106

[[main]]
  name = "Home Lab"
  url = "homelab/"
  weight = -105

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/kkramineni"
[[social]]
  name = "youtube"
  weight = 2
  url = "https://www.youtube.com/@cloud_bricks"
